#! /usr/bin/env node

const Hyperzone = require('hyperzone')

// ./create-dummy-zones tld sld.tld ...
const names = process.argv.slice(2).map(name => name[name.length - 1] === '.' ? name : name + '.')

main ()
async function main () {
  if (names.length === 0) return

  await Promise.all(names.map(async name => {
    // create zones with dummy records
    const zone = new Hyperzone(names, `./data/${name}`)
    await zone.ready()

    // print public key
    console.log(zone.key.toString('hex'))

    // insert records

    const batch = []

    // A record
    batch.push({ key: `A/0`, value: `${zone.name} 3600 IN A 66.42.108.201` })

    // TXT records
    batch.push({ key: `TXT/0`, value: `${zone.name} 0 IN TXT "hello world ${0} <3 ${zone.name}"` })
    batch.push({ key: `TXT/1`, value: `${zone.name} 0 IN TXT "hello world ${1} <3 ${zone.name}"` })

    zone.db.batch(batch)
  }))
}
